# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Utility' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
pod 'Alamofire'
pod 'Kingfisher’
pod 'SwiftyJSON'
pod 'HandyJSON’
pod 'SnapKit'
pod 'Moya'

  # Pods for Utility

end
